services:
  # A Docker web service
  - type: web
    name: alist
    env: docker
    repo: https://github.ink/CatNoSoul/Lunar-Cloud.git # optional
    region: singapore # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
          value: 5232
      - key: DB_TYPE
          value: mysql
        sync: false
      - key: DB_HOST
          value: db4free.net
        sync: false
      - key: DB_PORT
        v  alue: 3306
        sync: false
      - key: DB_USER
          value: styleadmin
        sync: false
      - key: DB_PASS
          value: 223754fc
        sync: false
      - key: DB_NAME
          value: stylenetwork
        sync: false
      - key: DB_TABLE_PREFIX
          value: alist_
        sync: false
      - key: CDN
          value: https://npm.elemecdn.com/alist-web@$version/dist
        sync: false
